In [2]:
import numpy as np
arr= np.arange(0,11)
arr




array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [4]:
arr_copy= arr.copy()
arr_copy 

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

SyntaxError: invalid syntax (51117737.py, line 1)